apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: hw7k9g3x9-nodejs 
  janus-idp.io/tekton: hw7k9g3x9-nodejs
  backstage.io/kubernetes-id: hw7k9g3x9-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: hw7k9g3x9-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml