apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: hw7k9g3x9-nodejs
  janus-idp.io/tekton: hw7k9g3x9-nodejs
  backstage.io/kubernetes-id: hw7k9g3x9-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: hw7k9g3x9-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
