apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: hw7k9g3x9-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hw7k9g3x9-nodejs 
  name: hw7k9g3x9-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: hw7k9g3x9-nodejs 
